### ISSUE TITLE
404 page not mobile optimized

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/html-app#2]
Title pretty much explains. Do you think we could make it look better on mobile?

**Comment by zspri** [comment]
Will do.

**Comment by zspri** [comment]
Done!
![capture](https://cloud.githubusercontent.com/assets/19719195/23234045/d167b34a-f91e-11e6-9891-7a3f4d30cfcc.PNG)

**Comment by coke11** [comment]
Awesome, thanks

**Comment by zspri** [comment]
No problem
